CREATE TABLE `white_label` (
	`id` text PRIMARY KEY DEFAULT 'site' NOT NULL,
	`custom_logo_key` text,
	`custom_platform_name` text,
	`footer_attribution` text DEFAULT 'default' NOT NULL,
	`custom_footer_text` text,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `legal_docs` (
	`id` text PRIMARY KEY NOT NULL,
	`body_html` text NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL
);
--> statement-breakpoint
INSERT INTO `white_label` (`id`, `footer_attribution`) VALUES ('site', 'default');
--> statement-breakpoint
INSERT INTO `legal_docs` (`id`, `body_html`) VALUES ('privacy', '<div class="howlcast-legal-banner"><strong>⚠ Placeholder text.</strong> This was auto-generated. Review and customize before going live with real users.</div><h2>Operator</h2><p>HowlCast is operated by <strong>MrDemonWolf, Inc.</strong> Contact: legal@mrdemonwolf.com.</p><h2>What we collect</h2><ul><li>Account: email, display name, username, hashed password.</li><li>Auth: passkeys (public keys only), 2FA secrets, session cookies.</li><li>Chat: messages you send via the embedded chat (stored by GetStream).</li><li>Stream metadata: when streams started/ended, total minutes (no recordings).</li><li>Operational logs: IP, user agent, request paths — kept ≤ 30 days.</li></ul><h2>What we don''t collect</h2><ul><li>No video recordings. HowlCast is live-only, no VODs.</li><li>No third-party trackers, ad networks, or behavioural analytics.</li><li>No payment data — HowlCast is invite-only and free to viewers.</li></ul><h2>Sub-processors</h2><p>HowlCast relies on the following third-party services to operate. Each acts as a sub-processor of your data:</p><ul><li><strong>Cloudflare</strong> — hosting, DNS, edge compute, D1 database.</li><li><strong>GetStream</strong> — live video transport, chat messaging, moderation tools.</li><li><strong>Resend</strong> — magic-link and invite email delivery.</li><li><strong>Twitch Helix</strong> — read-only emote and channel lookup at setup time.</li></ul><h2>Your rights</h2><p>You can request a copy of your data, correct it, or have it deleted by emailing legal@mrdemonwolf.com. Account deletion removes your profile, sessions, and chat identity within 30 days.</p><h2>Cookies</h2><p>HowlCast uses one essential cookie to keep you signed in. No advertising cookies, no cross-site tracking.</p><h2>Changes</h2><p>This policy may change. Material changes are announced in the channel before they take effect.</p>');
--> statement-breakpoint
INSERT INTO `legal_docs` (`id`, `body_html`) VALUES ('terms', '<div class="howlcast-legal-banner"><strong>⚠ Placeholder text.</strong> This was auto-generated. Review and customize before going live with real users.</div><h2>Acceptance</h2><p>By using HowlCast you agree to these terms. If you don''t agree, don''t use the service.</p><h2>Account and access</h2><p>HowlCast is invite-only. The broadcaster controls who receives invites; viewers without an invite can watch but not post. You''re responsible for keeping your sign-in credentials secure.</p><h2>Acceptable use</h2><ul><li>No harassment, hate speech, or threats targeting any person or group.</li><li>No illegal content (CSAM, real violence, infringing material).</li><li>No spam, scams, scraping, or automated abuse of the platform.</li><li>No attempt to disrupt the service (DDoS, exploit probing without authorization).</li></ul><p>Violations get you banned from the channel and possibly removed from the service. Severe violations are reported to law enforcement.</p><h2>Content ownership</h2><p>You keep the rights to anything you post. By posting in chat you grant HowlCast a non-exclusive license to display your messages within the channel for as long as the channel exists. HowlCast doesn''t record, store, or redistribute the broadcaster''s video stream — it''s live-only.</p><h2>Moderation</h2><p>The broadcaster has full moderation authority over chat and viewer access using GetStream''s built-in tools (ban, mute, slow mode, profanity filter). Decisions are final.</p><h2>Service availability</h2><p>HowlCast is provided "as is" with no uptime guarantee. We use Cloudflare and GetStream; outages in either may interrupt the service. We aren''t liable for losses caused by downtime, missed streams, or chat unavailability.</p><h2>Termination</h2><p>You can delete your account anytime by emailing legal@mrdemonwolf.com. We can suspend or terminate accounts that violate these terms.</p><h2>Changes</h2><p>We may update these terms. Material changes are announced in the channel before they take effect. Continued use after changes means you accept the new terms.</p>');
